travis:
  secure:
    BINSTAR_TOKEN: XB1orwyNrvFEzQD8iLrx6DbSYYtUHAJR+o1xD89V2fxONEuVUiEoE35iICWflhXDpeoEo5E4egdUjAG865Q62Xq5zwmu7h+triPCvmXueIjtBstS8UWIeY/7yn2AFr0Q/gpPB3bt3bR+SvfoSTn2OqEHOhnb6ZAgcYIZ/9Bm4GTAEzxdasGITEIU81ElxfrxjKM1i53WdzAke1VCvlOIG5pDLpujmx2/AP5ceJrSKPt+5QYFHfR7wFlz+DRQVlDeBXweEtdQ8mTtm8iOaUDsOkj9/zlGJvFewccOXvLgPBi1CHk4nl/9X/VtzNJhK7b9oau7j3kI5u7JbJ5MUKDWAxGHwl90Vj43fgnNnQqcYI4zNHh81Ys7AtaSxDlVb76PcSMjoDCrLIM7kn3yKLty4jkWhh4wIdNmG5K887R2JYxZQUw4ieGiOBDiIkT90AePXDZ9HLIPnCQj6cTkKtB9Pq3VL995VHWCk9xFdLuno6eDJm+bhNofBSB4wDgw/hDqkftOEJkWpWPAH+OuFeDnHPj9M/RaX0ySS1wLK4GL4FPaUo8aq5PxUgt0gC5ADcoN9n+VQIkHdTpPzjHx/auSX/DvFBDVV1vKI59N7auieS93/fbyhg0NUBFI5DxeW7j5RoGmcV0dIv93XQSk8aGtmFVMTWUQP6FCGCOKu//7dPk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
